### ISSUE TITLE
Wrong output when EPRINTTYPE is present and NUMBER is absent

### ISSUE THREAD

**Issue by rmolina** [plk/biblatex-apa#107]
The output for the following MWE is missing a comma:

```latex
\documentclass{article}
\usepackage[style=apa]{biblatex}
\addbibresource{\jobname.bib}
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
% (APA 10.1 Example 6)
@ARTICLE{10.1:6,
  AUTHOR         = {D. Burin and K. Kilteni and M. Rabuffetti and M. Slater and L. Pia},
  TITLE          = {Body Ownership Increases the Interference Between
                    Observed and Executed Movements},
  JOURNALTITLE   = {{PLOS ONE}},
  VOLUME         = {14},
  %NUMBER         = {1},
  DATE           = {2019},
  EPRINTTYPE     = {article},
  EPRINT         = {e0209899},
  DOI            = {10.1371/journal.pone.0209899}
}
\end{filecontents}

\begin{document}
\cite{10.1:6}
\printbibliography
\end{document}
```
The comma is there when the NUMBER field is uncommented.

**Comment by moewew** [comment]
The standard styles would use `eid` instead of `eprint` here. PR #108 implements that and fixes the punctuation issue.

**Comment by moewew** [comment]
I wanted to implement the same for `biblatex-apa6`, but according to https://blog.apastyle.org/apastyle/2015/05/how-to-cite-an-article-with-an-article-number-instead-of-a-page-range.html and the clarifications in the comments below the blog post, **the official APA position in 6th edition style is to ignore the article number/`eid`**, so I will not port #108 to `biblatex-apa6`.

Because my Firefox had a hard time loading the comments, I will reproduce them here

![apastyleblog](https://user-images.githubusercontent.com/6755835/80864517-759c3f80-8c83-11ea-8a14-3e5b3f8017bf.PNG)


> [Carrie, 2016-06-06T12:19] Hi. I'm interested in the referencing for the Frontiers in Psychology journal as I have about 6 articles to reference from the same journal. One article I want to reference says Volume 4, Article 625. When I download a PDF it has page numbers at the bottom of the page 1 through 25. As per above recommendations I'm not sure if I should use the first or second example below, but neither include the article number? When downloading the citation from the journal it gives it as the third example shown. Can you please point me in the right direction? I guess I'm not sure whether to include the article number or not in the citation - I imagine I should? Thanks for your help! 
>
> ... Frontiers in Psychology, 4.
> ... Frontiers in Psychology, 4, 1-25.
> ... Frontiers in Psychology, 4, 625.

> [Chelsea Lee (blog post author), 2016-06-06T13:47]
> Use the page range:
> Frontiers in Psychology, 4, 1-25.
