### ISSUE TITLE
Chapters in books in series with volumes not supported using correct biblatex fields

### ISSUE THREAD

**Issue by andersjohansson** [plk/biblatex-apa#15]
I guess this is part of very general stuff that has to be done. There is an example for 7.02:24 in the test-file, and the bib item is:

```
@INBOOK{7.02:24,
  AUTHOR         = {Strong, Jr., E. K. and R. S. Uhrbrock},
  EDITORA        = {L. Outhwaite},
  EDITORATYPE    = {series},
  TITLE          = {Bibliography in Job Analysis},
  BOOKTITLE      = {Personnel {R}esearch {S}eries},
  BOOKSUBTITLE   = {Vol. 1. {J}ob Analysis and the Curriculum},
  PAGES          = {140--146},
  DATE           = {1923},
  DOI            = {10.1037/10762-000}
}
```

But supporting the full modern biblatex fields (isn't that expected by biblatex-apa?) this should be:

```
@INBOOK{7.02:24,
  AUTHOR         = {Strong, Jr., E. K. and R. S. Uhrbrock},
  EDITORA        = {L. Outhwaite},
  EDITORATYPE    = {series},
  TITLE          = {Bibliography in Job Analysis},
  BOOKTITLE      = {{J}ob Analysis and the Curriculum},
  SERIES   = {Personnel {R}esearch {S}eries},
  NUMBER = {1},
  PAGES          = {140--146},
  DATE           = {1923},
  DOI            = {10.1037/10762-000}
}
```

and give the same results. I suppose this may mean a lot of new processing has to be added and I'm definitely not going to write a patch today. I'll fake it for now (sending in thesis tomorrow!).

BTW @plk, someone seems to think you are not with us anymore: https://www.ctan.org/author/kime. Did that really happen the last two weeks? A great loss in that case.

**Comment by plk** [comment]
I'll look into that when I have time. I am not deceased ... I have mailed the CTAN people ...

**Comment by andersjohansson** [comment]
Thanks, just raising the issue...
Maybe they mixed you up with Phillip Lehman who is gone (or impossible to reach?) as far as I understand.

**Comment by plk** [comment]
That's true and I thought that too but they tell me that it happened suddenly to all CPAN authors ...

**Comment by andersjohansson** [comment]
Is this really fixed? Or impossible to solve? I looked through the commits and couldn’t see anything applying to this.

No big problem though, I’ll just use fake it with booksubtitle again! (just stumbled upon the issue again since it is time to send in my complete PhD thesis in a few days! Last time was the Swedish "half time thesis").

**Comment by sbibauw** [comment]
I am also frustrated by the way `biblatex-apa` is treating the `number` field in `@incollection` entries: it should be treated as Series number (as per `biblatex` documentation, § 2.2.2/ p. 22: "The number of a journal or the volume/number of a book _in a series_."), but is used as the `volume` field.
Because my BibTeX file is automatically exported from Zotero, it is quite painful to try to correct each of these entries manually. Will the style be corrected or is there a fix for this?

**Comment by moewew** [comment]
It is often a bit of a judgement call whether something is a `series`+`number` or a `maintitle`+`volume` combination.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

%\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@inbook{7.02:24,
  author         = {Strong, Jr., E. K. and R. S. Uhrbrock},
  editora        = {L. Outhwaite},
  editoratype    = {series},
  title          = {Bibliography in Job Analysis},
  booktitle      = {Job Analysis and the Curriculum},
  maintitle      = {Personnel Research Series},
  volume         = {1},
  pages          = {140--146},
  date           = {1923},
  doi            = {10.1037/10762-000}
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,7.02:24}
\printbibliography
\end{document}
```
seems to give acceptable output. I don't have the APA manual handy, but it is not clear to me whether there are other examples of `series`+`number` usage to be found there or if everything they do can be expressed with `maintitle`+`volume`. 

If that is the case you may as well remap the fields.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

\DeclareSourcemap{
  \maps[datatype=bibtex, overwrite=false]{
    \map{
      \step[fieldsource=series, final]
      \step[fieldset=maintitle, origfieldval, final]
      \step[fieldset=series, null]
      \step[fieldsource=number, final]
      \step[fieldset=volume, origfieldval, final]
      \step[fieldset=number, null]
    }
  }
}

%\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@inbook{7.02:24,
  author         = {Strong, Jr., E. K. and R. S. Uhrbrock},
  editora        = {L. Outhwaite},
  editoratype    = {series},
  title          = {Bibliography in Job Analysis},
  booktitle      = {Job Analysis and the Curriculum},
  series         = {Personnel Research Series},
  number         = {1},
  pages          = {140--146},
  date           = {1923},
  doi            = {10.1037/10762-000}
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,7.02:24}
\printbibliography
\end{document}
```

If the APA manual has usage of `series`+`number` more akin to that of standard `biblatex`, the style should probably be adjusted. I could do that, but I would need the relevant bits and pieces of the APA manual and examples.

**Comment by sbibauw** [comment]
@moewew Thank you for your response.

First, yes, using `maintitle` and `volume` produces adequate results (well, to be perfectly exact: `maintitle` should be printed in Title Case [as per APA Manual 6th ed., p. 204: "In regularly published series with subtitles that change regularly, the series title is uppercase and the subtitle is lowercase, as in a book title."], and is printed in Sentence case, but this is not a big deal). 

Now, using `series` and `number` does not produce adequate results (nor does using `series` and `volume`, or `maintitle` and `number`): `series` is added after the `booktitle` (and `pages` range), and `number` is added inside the parenthesis for volume and `pages`.  

I have searched the whole 6th edition of the APA Publication Manual, the only mention of "series" or "collection" is for this specific case (Strong & Uhrbrock, 1923): "Electronic version of book chapter in a volume in a series". Which is slightly weird, because many Series/Collection nowadays are not such an important part of the reference that it should precede the book title as a `maintitle`, and I thought that the series should be added after the book title, as documented [in these instructions from University of Illinois](http://www.cws.illinois.edu/workshop/writers/citation/apa/bookinseries/) (but it seems to be based upon the 5th edition and I don't find any exemplar to check that). In any case, this inclusion of the `series` title after the book title is *not* documented in the 6th edition, and should thus probably be removed from `biblatex-apa`.

In any case, I believe `biblatex-apa` should:
- maintain its use of `maintitle` and `volume`,
- use `series` and `number` in the same way as `maintitle` and `volume` (or possibly use it as now - following 5th edition? - as a complement after `booktitle`, but including `number`: `author` (`year`). *`booktitle`*. `series`, `number`. `location`: `publisher`.)
- in any case, avoid using `number` inside the parenthesis for chapters/pages.

**Comment by sbibauw** [comment]
@plk: Any chance of seeing this issue of `number` being erroneously identified as `volume` solved? 

All the standard `biblatex` default bibliography styles are actually doing it correctly, among other things with `\newbibmacro*{series+number}` in [standard.bbx](https://github.com/plk/biblatex/blob/67174dbab53ec68938b9473bb64f096c117c183e/tex/latex/biblatex/bbx/standard.bbx#L853).

In `biblatex-apa`, if I understand the source correctly, I would remove the inclusion of `field{number}` in `apa.bbx`, at line [672](https://github.com/plk/biblatex-apa/blob/a2311a831faae8fa4ecd28e1163015f05f60ba2a/tex/latex/biblatex-apa/bbx/apa.bbx#L672), possibly also [952](https://github.com/plk/biblatex-apa/blob/a2311a831faae8fa4ecd28e1163015f05f60ba2a/tex/latex/biblatex-apa/bbx/apa.bbx#L952) and 971,  and adding the `number` to the `series` mention later on (or rather remove the subsequent mention of `series` completely actually, since there is no mention of the need to include series/collection information in the APA manual beyond the unique case mentionned by @andersjohansson).

**Comment by plk** [comment]
Please can you try v8.0 here:

https://www.dropbox.com/s/nrfivrgalrr1m4s/biblatex-apa.tgz?dl=0

if it's alright, I will release. In the coming months when APA 7th Ed is released, I will be updating to correspond to this.

**Comment by sbibauw** [comment]
> @sbibauw - Please can you try v8.0 here:
> https://www.dropbox.com/s/nrfivrgalrr1m4s/biblatex-apa.tgz?dl=0

Yes, it solves the issue completely. Removes all unwanted uses of Series (including as a form of "subtitle" for special journal issue, which also was not described in the APA guidelines), so all good for me! Thank you very much!

**Comment by plk** [comment]
8.0 has been uploaded to CTAN.
