### ISSUE TITLE
In-text citations should have years in parenthesis 

### ISSUE THREAD

**Issue by mikaelsrozee** [plk/biblatex-apa#151]
For in-line citations, from what I've seen, APAv7 guidance says that they should follow the format `<author(s)> (<year>)` however my files are being compiled to `<author(s)> <year>` (note the lack of parenthesis).

src:
```latex
\cite{Fowler1999} stress the importance of writing code that is readable by a human. Readability is not the only benefit of following a style guide. \cite{Zou2019} find that, for pull requests on open source projects, code that follows the style guide of the main codebase is easier to merge and faster to decline.
```

output:
```
Fowler et al., 1999 stress the importance of writing code that is readable bya human.  Readability is not the only benefit of following a style guide.  Zouet al.,  2019 find that,  for pull requests on open source projects,  code thatfollows the style guide of the main codebase is easier to merge and faster todecline.
```

expected output:
```
Fowler et al., (1999) stress the importance of writing code that is readable bya human.  Readability is not the only benefit of following a style guide.  Zouet al.,  (2019) find that,  for pull requests on open source projects,  code thatfollows the style guide of the main codebase is easier to merge and faster todecline.
```

guidance src: https://library.port.ac.uk/ref/page714.html#t714

Let me know if this is an issue with this project, or incorrect guidance. Thanks!

**Comment by moewew** [comment]
Use `\parencite` for parenthetical citations and `\textcite` for narrative citations (in APA-speak: https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/parenthetical-versus-narrative).

If you are using a `\...cite` command at the beginning of a sentence, capitalise its first letter (e.g. `\Textcite` instead of `\textcite`) in order to obtain correct capitalisation of the cite output.

```latex
\documentclass[american]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=apa]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem ipsum \parencite{sigfridsson}.

Then, \textcite{sigfridsson} showed that \dots

\Textcite{sigfridsson} argue that \dots

\printbibliography
\end{document}
``` 
> Lorem ipsum (Sigfridsson & Ryde, 1998).
> Then, Sigfridsson and Ryde (1998) showed that ...
> Sigfridsson and Ryde (1998) argue that ...

![screenshot of the output quoted above](https://user-images.githubusercontent.com/6755835/139593205-a5107398-3dc1-4ac0-8a57-b33f26e8e795.png)

----

You can use `\nptextcite` for citations in manually generated/typeset parentheses.

```latex
(e.g., falsely balanced news coverage; \nptextcite{sigfridsson})
```

**Comment by mikaelsrozee** [comment]
Thank you @moewew!
