### ISSUE TITLE
Oxford commas in bibliography even with `\usepackage[ngerman]{babel}`

### ISSUE THREAD

**Issue by apopqo** [plk/biblatex-apa#191]
First of all, many thanks to all maintainers and contributors for maintaining this package.

Sorry in advance in case I just have a comprehension problem. But as I understand #22, actually since 2016 commas should not appear before final "and"s between author names when `babel` is, e.g., loaded with the `ngerman` option. Does this perhaps only refer to author naming in text, e.g. via `\textcite` or `\parencite`? In the bibliography I still get Oxford commas, e.g. with the following LaTeX document:

```latex
\documentclass{article}

\usepackage[ngerman]{babel}
\usepackage[style=apa]{biblatex}
\usepackage{csquotes}

\begin{filecontents}{bib.bib}
@book{book,
  title = {Book},
  author = {Author, Alice and Author, Bob},
  date = {2022},
  publisher = {Publisher}
}
\end{filecontents}

\addbibresource{bib.bib}

\begin{document}

\textcite{book}

\printbibliography

\end{document}
```

The DGPs guidelines, already mentioned in #22, require, I believe, that there are no commas before "&"s in the bibliography either. Therefore my question: Is this possibly a bug or have I not understood something fundamental?

Thanks in advance for any feedback!

**Comment by moewew** [comment]
IIRC the comma you are seeing in the list of references before the "&" in the author name is not technically implemented as an Oxford comma. A while ago the argument was made that the given name initials should conceptually be treated like a parenthesis and should therefore at all times be set off with two commas. Of course in most cases it is impossible to tell whether the commas we are seeing are those of the parenthesis, those that we get because we list different names, or Oxford commas. There is some discussion in https://github.com/plk/biblatex-apa/issues/48 and https://tex.stackexchange.com/q/417648/35864.

It is possible that DGP requirements are different (possibly because they do not agree with the reading laid out here). But before we do anything here, it might be useful to review both the official APA rules as well as DGP guidelines carefully (and possibly ask DGP for clarification).

**Comment by apopqo** [comment]
Thank you for your reply. Unfortunately, I don't have a copy of the current APA guidelines. However, looking at https://apastyle.apa.org/style-grammar-guidelines/references/elements-list-entry#author it seems to me that for English (or strict APA) reference lists it is correct to use a comma before the "&", even if there are only two authors. Which AFAICS was covered in #48. According to https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/author-date it is also correct to use no comma before "&"s in in-text citations, I would say. So, for English citations and reference lists `biblatex-apa` correctly sets/omits commas before "&"s, I think.

The German variant of the APA guidelines published by the Deutsche Gesellschaft für Psychologie (DGPs), however, explicitly does not allow commas before "&"s in the reference list (the following is a translation by myself):

> The last author name is preceded by the ampersand (&) without a preceding comma (deviating from APA, 2010).

A side note: The DGPs manual's latest edition is from 2019 and is thus based on the sixth edition of the APA manual.

For in-text citations the DPGs manual does not explicitly disallow preceding commas. However, all examples given in the manual are written without commas before the "&"s (which is also what `biblatex-apa` does for German in-text citations).

**Comment by apopqo** [comment]
You explained in https://tex.stackexchange.com/a/417906/270854 that you "define[d] a new `finalnamedelim:apa:family-given`". When I search for this term inside the texlive installation on my machine, I only find it inside a bbx file under `biblatex-apa6`. When I use `apa6` instead of `apa` inside my LaTeX document, the commas are not there for `ngerman` (they are there for `english`).

Maybe the interals of `biblatex-apa` are very different from those of `biblatex-apa6`, and `finalnamedelim:apa:family-given` would not make sense in `biblatex-apa`, but I thought it was worth mentioning the different results.

**Comment by moewew** [comment]
Yeah, some of that code was changed in https://github.com/plk/biblatex-apa/pull/144 to simplify other things. The code now follows the logic that the given name initials are a parenthesis and does not use any pre-existing `biblatex` Oxford comma code any more.

I guess if you want to follow DGPs at the moment you want to use `biblatex-apa6` anyway, but maybe you can contact them and ask them to consider this issue once they update their recommendations to APA7.

**Comment by apopqo** [comment]
You are right, for DGPs style citations and reference lists `biblatex-apa6` should be used, as DGPs has not yet defined how to apply APA7 guidelines in their terms. I'm closing this issue then. Thank you for your help and clarification!

**Comment by moewew** [comment]
Though I guess unless someone gets into contact with DGPs a similar issue will arise once the new recommendations are out.

**Comment by apopqo** [comment]
That's a good point, of course. I've just written an email to the main contact person I found on their website and asked for information regarding the new recommendations. As soon as I have an answer, I will record the relevant information here.

**Comment by moewew** [comment]
Great!

I'm not particularly hopeful that they will agree with the interpretation of APA style that presumes that given names need to be set off with commas at all times because the comma before an "and"/"&" looks pretty alien in German. So in all likelihood we will need to find a way to accommodate for that. Still maybe, just maybe ...

**Comment by PsychicBirdy** [comment]
Here are my two cents. From a semantic point of view it is quite clear that the initials at the beginning of a reference entry are subunits and thus that is the reason why they are separated by commas. That is, the initials are not of the same importance as the given names when it comes to ordering references. For example, have a look at example 43:

> Sacchett, C., & Humphreys, G. W. (2004). Calling a squirrel and squirrel but a canoe a wigwam: category-specific deficit for artefactual objects and body parts. In D. A. Balota & E. J. Marsh (Eds.), Cognitive psychology: Key readings in cognition (pp. 100–108). Psychology Press. ...

"D. A. Balota" and "J. Marsh" each count as one unit. Thus, we only have two units here and there isn't any Oxford comma after "Balota", neither in English nor in German. Now it doesn't make any sense to count "Sacchett" and "C." as two independent units just because the order is reversed. The initial is bracketed here because it's not the usual order (initials then given name) and thus it is treated as a subunit of the whole name construction. These are bracketing commas. We don't have an Oxford comma here, otherwise this would mean that "Sacchett", "C.", and "Humphreys" would all be of same importance. If we would have an Oxford comma here, it would look like this: "Sacchett, C., Humphreys, & G. W."

So I believe the solution we have right now is a good one. The DGP manual just got the semantic meaning of the commas wrong here. The DGP manual isn't a faithful translation of the APA style in other regards either. So I guess we shouldn't follow it too closely when localizing biblatex-apa.

**Comment by apopqo** [comment]
I'm trying to understand this, but I'm not quite sure I'm on the right track. Is it about the fact that the initials are kind of syntactically postponed and one would also in a normal sentence separate such a postponement in front and behind by commas? So not using a comma before the "&" would be like writing "Person A, the smaller one and Person B, the taller one"?

**Comment by PsychicBirdy** [comment]
Yes, that is an apposite comparison.

**Comment by apopqo** [comment]
Then I completely agree with you that in all cases, no matter what language, should a comma be placed before the "&"s in the list of references (when listing names in the order: given name, initials). Thank you for the insight!

If I a should be able to get in touch with a person at DGPs who is somehow involved in writing their guidelines, yeah, well, ... I think I will try to convince them not to specify the omission of the comma in the next version. Not sure if they will listen to some random guy writing them emails, but you never know.

So, I think I'm going to close this issue again then.

Thank you very much for the conversation and for maintaining `biblatex-apa`!
