### ISSUE TITLE
Bad formatting of @inreference works with no author where the reference work itself has an editor

### ISSUE THREAD

**Issue by logological** [plk/biblatex-apa#192]
According to my understanding of §§8.14, 9.12, and 9.49 of the APA Publication Manual (7th edition), if a work has a title but no author, then

1. Its title should be used when citing the work.
2. In the reference list, the title should move to the author position.
3. In the reference list, the title should serve as the sort key.

biblatex-apa does all this correctly for `@incollection` and `@inreference` entries where there is no author and the collection/reference work as a whole has no editor, but it does not do this correctly if the collection/reference work as a whole does have an editor.  Instead, we see that

1. The editor gets used when citing the work.
2. In the reference list, the editor moves to the author position.
3. In the reference list, the editor serves as the sort key.

Take the following minimal example:

```
\documentclass{article}

\begin{filecontents}{\jobname.bib}
@inreference{cleveland,
  title	       = {Cleveland {FreeNet}},
  year	       = 2022,
  booktitle    = {Encyclopedia of {Cleveland} History},
  editor       = {John J. Grabowski},
  publisher    = {Case Western Reserve University},
}

@book{driscoll,
  author       = {Kevin Driscoll},
  title        = {Some Book},
  year         = 2022,
}
\end{filecontents}

\usepackage[style=apa,backend=biber]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\autocite{cleveland,driscoll}
\printbibliography
\end{document}
```

Here I expect the following output:

> (“Cleveland FreeNet”, 2022; Driscoll, 2022)
>
> **References**
> Cleveland FreeNet (2022). In J. J. Grabowski (Ed.), _Encyclopedia of Cleveland history._ Case Western Reserve University.
> Driscoll, K. (2022). _Some book._

Instead, I get the following output:

> (Driscoll, 2022; Grabowski, 2022)
>
> **References**
> Driscoll, K. (2022). _Some book._
> Grabowski, J. J. (Ed.). (2022). Cleveland FreeNet. In _Encyclopedia of Cleveland history._ Case Western Reserve University.

**Comment by plk** [comment]
Hmm, I'm not sure about this - the "no author" sections in the APA 7th seem to be referring to simpler cases of things like religious texts, anonymous texts etc. and not edited volumes which do have a natural replacement for the "author" position. This might need clarifying on the APA blog - they are usually fairly swift to rule on such cases.

**Comment by logological** [comment]
I don't see any way of submitting questions to the APA blog.  I've written to the APA style team by e-mail and will let you know their response.

**Comment by logological** [comment]
I received a response to my query from Stefanie Leisure of the APA. The relevant parts of the reply (which addresses the same real-world example as in this issue report) read as follows:

> Yes, the rules still apply even when the source has an editor. The editor does not move to the author position of the reference when the encyclopedia entry does not have a named author.
>
> A few suggestions for the reference: […]
>
> Cleveland Freenet. (n.d.). In J. J. Grabowski (Ed.), Encyclopedia of Cleveland history. Case Western Reserve University. Retrieved September 28, 2022, from https://case.edu/ech/articles/c/cleveland-freenet
>
> The in-text citation would be ("Cleveland Freenet," n.d.). Note that the comma goes inside the quotation marks.

(The ellipses in the quotation above are the omission of a lengthy aside of hers where she argues that the year should not be cited, and a retrieval date should be added, since the encyclopedia in question is continuously updated.)

**Comment by plk** [comment]
Hmm, this is typical of the APA - they haven't really though about the fact that their style could be automated and their comments are mostly interpretable as guidance or manual modification. See the examples in section of 10.1 in the APA 7th manual where there is no author, there is an editor and a title but the title is not in the author position ... the editor is. Unless we have clear guidelines from them on which, say, entry types are supposed to follow the "use the title, not editor" rule, this feels rather arbitrary.

**Comment by PsychicBirdy** [comment]
I don't think that their comment is a manual modification. I think the case is pretty clear. It's all about what you are actually referring to, be it an article, a special issue of a journal, a book, or a book chapter. In any case, the writer(s) of _the work in question_ (if the work is not anonymous) go in front. If the work is anonymous, the title goes in front.

I guess you are referring to section 10.1, examples 12a (Lilienfeld) and b (McDaniel et al.). You are saying there is no author, there is an editor and a title but the title is not in the author position, the editor is. Well, what matters here is not whether we are dealing with authors or editors, but who is responsible for the _**work in question**_ - in this case special issues of journals. These are usually edited works, so the editors go in front.

The situation is different if we are talking about book chapters in edited works. In such a case, we now have at least two kind of writers, the author of the chapter and the editor of the overall book the chapter is a part of. Again, this is not about author or editor (that's just a specification we make), it's about who is responsible for _**the work in question**_, _**the chapter**_. Now if the chapter is written anonymously and the book has an editor who is mentioned, still the title of the chapter goes in front because its author is anonymous. If we would put the editor of the book in front, we would get confused and think this is some kind of edited chapter in a book the editor of which isn't mentioned.

So for articles, books, special issues of journals and so on, we only have one kind of writer(s), so if he work isn't anonymous, the writer(s) go in front, and we specify whether they are authors or editors. For book chapters, articles in reference works and so on, we have two kind of writer(s), and if the author(s) of the chapter, the article and so on are anonymous, the chapter/article title goes in front and the book/reference editor(s) stay where they are.

**Comment by plk** [comment]
I see the semantic difference but for automation, it's a bit more involved as we have to change `labelname` and sorting templates too. I have put something into the master branch on Git for this which solves your problem and passes all regression tests so far.
