### ISSUE TITLE
behavior on capitalization

### ISSUE THREAD

**Issue by dkwo** [plk/biblatex-apa#201]
If not using `\DeclareFieldFormat{apacase}{#1}`, then all capital letters are converted to small, except for the first one: is this behavior intentional or a bug?

Incidentally: I get the warning `Package biblatex Warning: The starred command '\DeclareDelimAlias*' is deprecated. Use the unstarred version '\DeclareDelimAlias' instead.` (I cannot reproduce the issue locally with texlive 2021, but I got it e.g. on Overleaf using texlive 2022.)

Here's an example:
```
\documentclass[english, 12pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{babel}
\usepackage{microtype}
\usepackage{csquotes}
\usepackage{lmodern}
\usepackage[style=apa]{biblatex}
% \DeclareFieldFormat{apacase}{#1}
\usepackage{setspace}
\usepackage{hyperref}
\usepackage{array}

\begin{filecontents}{test.bib}
@book{cefis,
	title = {Some Words like London: Public test Capital in {L}ondon},
	publisher = {Cambridge University Press},
	author = {Doe Jonathan},
	date = {2020},
}
\end{filecontents}
\addbibresource{test.bib}

\begin{document}
test the issue with \parencite{cefis}

\printbibliography
\end{document}
```

Thanks.

**Comment by moewew** [comment]
The capitalisation you see is intentional. As explained in https://apastyle.apa.org/style-grammar-guidelines/references/elements-list-entry#title titles of non-standalone works should be given in sentence case. (Do note that Names, proper nouns, abbreviations etc. may have to be protected from capitalisation change with curly braces, see https://tex.stackexchange.com/q/10772/35864).

The warning you quote has been fixed (https://github.com/plk/biblatex-apa/issues/125), but it has always been benign and can be ignored. Apparently your local system is too old for the issue while Overleaf does not have the newest version of `biblatex-apa` with the fix.

**Comment by dkwo** [comment]
Many thanks for explaining this!
