### ISSUE TITLE
Integration of \textcite with multiple references

### ISSUE THREAD

**Issue by flindeberg** [plk/biblatex-apa#94]
`\textcite` with multiple references does not behave as expected, as the manual of BibLaTeX states "intended for use in the flow of text, replacing the subject of a sentence". Currently it is not possible to treat `\textcite` with multiple references easily as a narrative reference since you yourself have to keep track of references, order and possible location / existence of *and*.

I.e., to obtain " ... as argued in AuthorA (2001), AuthorB (2002) *and* AuthorC (2003)" you have to write 

`as argued in \textcite{authora}, \textcite{authorb} and \textcite{authorc}`

(or you could even write `as argued in \textcite{authora,authorb} and \textcite{authorc}`)

I think it should be possible to write `as argued in \textcite{authora,authorb,authorc}` and BibLaTeX(-APA) takes care of the actual formatting of the narrative reference. 

According to the APA-manual, as seen in the example document http://ftp.acc.umu.se/mirror/CTAN/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test.pdf, `\textcite{10.1:12a} and \textcite{10.1:12b}` should become "À Lilienfeld (2018) and McDaniel et al. (2018)" (using standard bibliographies), so why not allow for `\textcite{10.1:12a,10.1:12b}` to handle the issue?

I find this mostly infuriating when working with working papers, as you often change sources and references, and currently I manually have to take care of things if I remove the last reference or use more than one reference (sorting, punctuation, etc). It would be very nice if BibLaTeX-APA could handle it.

See https://tex.stackexchange.com/questions/28461/biblatex-tighter-integration-of-textcite-in-the-flow-of-text for the general BibLaTeX-case (which is fixed).

**Comment by moewew** [comment]
Somehow I expected that `biblatex-apa` already does this, but it doesn't. You'd think someone would have complained about that before, but no.

@plk I have something ready that copies the two-pass system from `authoryear-comp`, but before I submit a PR I would like to know about the status of `\nptextcite`. Should it really be based on `\textcite` (in which case more work would be needed) or should it rather be based on `\parencite`? See also https://github.com/plk/biblatex-apa/issues/78.

I could also look at https://github.com/plk/biblatex-apa/issues/90 while I'm at it, but it would help if someone could make a ruling on what the correct pre- and postnote position would be for `\textcite`.

**Comment by moewew** [comment]
I think so, yes. There are still some things to sort out.

Currently
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\textcite{sigfridsson,worman,geer}
\printbibliography
\end{document}
```
gives
> Geer (1985), Sigfridsson and Ryde (1998), Worman (2002)

There is no "and".

https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/multiple-works

> > Suliman (2018), Gutiérrez (2012, 2017), and Medina and Reyes (2019) examined . . .

Suggests there should be ", and", so we probably need to transplant code from `authoryear-comp`. I think I have something ready that might work, but it may or may not clash with `\nptextcite`.


So before we proceed we need to figure out what to do with `\nptextcite`. That's basically https://github.com/plk/biblatex-apa/issues/78, where we need to decide whether `\nptextcite` should be "`\parencite` without parens" or "`\textcite` without parens". Unfortunately, I could not find a clear statement that helps us decide between the two. I found

https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/parenthetical-versus-narrative

>  If other text appears with the parenthetical citation, use commas around the year.
>
>> (see Koehler, 2016, for more detail)
>
>When text and a citation appear together in parentheses, use a semicolon to separate the citation from the text; do not use parentheses within parentheses.
>
>>(e.g., falsely balanced news coverage; Koehler, 2016)

which unfortunately, doesn't say what happens with several citations, but since semicolons are used and this is in the section about `\parencite` I'm leaning towards basing `\nptextcite` on `\parencite`.

This question also ties into the first part of #90. What should happen to

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\textcite[see][380]{sigfridsson}

\textcite[380]{sigfridsson}

\textcite[see][]{sigfridsson}

\printbibliography
\end{document}
```
> see, Sigfridsson and Ryde (1998, p. 380)
> Sigfridsson and Ryde (1998, p. 380)
> see, Sigfridsson and Ryde (1998)

The comma after "see" looks wrong and other `authoryear`-based style move the prenote into the parentheses:
> Sigfridsson and Ryde (see 1998, p. 380)
> Sigfridsson and Ryde (1998, p. 380)
> Sigfridsson and Ryde (see 1998)

I'm not sure what the APA want here, I could not find any example of a "see" in a "narrative citation". But I could only find examples putting the page numbers somewhere else completely

https://apastyle.apa.org/style-grammar-guidelines/citations/paraphrasing

> Although it is not required to provide a page or paragraph number in the citation, you may include one (in addition to the author and year) when it would help interested readers locate the relevant passage within a long or complex work (e.g., a book).
>
>> Webster-Stratton (2016) described a case example of a 4-year-old girl who showed an insecure attachment to her mother; in working with the family dyad, the therapist focused on increasing the mother’s empathy for her child (pp. 152–153).

and https://apastyle.apa.org/style-grammar-guidelines/citations/quotations

>> Flores et al. (2018) described how they addressed potential researcher bias when working with an intersectional community of transgender people of color:
Everyone on the research team belonged to a stigmatized group but also held privileged identities. Throughout the research process, we attended to the ways in which our privileged and oppressed identities may have influenced the research process, findings, and presentation of results. (p. 311)


---

So my suggestion would be

- base `\textcite`  on `authoryear-comp`'s two-pass `\textcite` system,
- base `\nptextcite` on regular `\parencite` but drop the outer parentheses.

This should hopefully resolve #78, #90 and this issue here.

But the second part is still up for discussion.

**Comment by flindeberg** [comment]
My five cents on #90 is that the prenote should be outside the parenthesis for `\textcite` (and without the comma), i.e. 

> see Sigfridsson and Ryde (1998, p. 380)

My primary reason for this is that `see` inside the parenthesis does not make sense for multiple references.

**Comment by moewew** [comment]
> 
> 
> My five cents on #90 is that the prenote should be outside the parenthesis for `\textcite` (and without the comma), i.e.
> 
> > see Sigfridsson and Ryde (1998, p. 380)
> 
> My primary reason for this is that `see` inside the parenthesis does not make sense for multiple references.

Mhhh, I'm not sure. Obviously I'm biased by the behaviour of `\textcite` in the standard styles, but I can't really think of a situation where the prenote before the author name would make sense in "narrative citations" for the usual uses of the prenote argument. But I can sort of see some uses for a prenote in the parentheses. (Remember that in narrative citations the author names essentially form part of the surrounding sentence, while the year is added as a parenthetical remark. So I would probably want to argue that when you parse the sentence, `\textcite` should be seen as producing the author name only. In that setting it makes little sense to make `\textcite` produce additional words before or after the author name, because they would be a regular part of the sentence that should be typed as usual.)

In APA style you could not write

> see Sigfridsson and Ryde (1998)

a "see" like this would only be possible in a parenthetical citation

> (see Sigfridsson and Ryde, 1998)

A typical narrative citation would be

> this was considered by Sigfridsson and Ryde (1998)

I can imagine that a prenote could be employed like

> this was considered by Sigfridsson and Ryde (especially 1998)

or 

> this was considered by Sigfridsson and Ryde (e.g. 1998)

---

As to whether or not it's clear what a prenote would refer to, I think `authoryear-comp` gets this right when you use multi-cite commands
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear-comp, backend=biber]{biblatex}


\addbibresource{biblatex-examples.bib}


\begin{document}
\textcites(global-pre)(global-post)[pre][post]{sigfridsson}[pre][post]{nussbaum}
\printbibliography
\end{document}
```
> global-pre Sigfridsson and Ryde (pre 1998, post) and Nussbaum (pre 1978, post), global-post

When you don't use multi-cite commands it is always a bit tricky to tell what pre- and postnote refer to exactly. Even more so when `sortcites` is active.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear-comp, backend=biber]{biblatex}


\addbibresource{biblatex-examples.bib}


\begin{document}
\parencite[380]{sigfridsson,nussbaum}
\printbibliography
\end{document}
```

**Comment by flindeberg** [comment]
I buy your argument completely @moewew !

**Comment by moewew** [comment]
My suggestion to resolve issues #78, #90 and #94 (this issue) by basing `\textcite` on `authoryear-comp`'s two-pass `\textcite` and `\nptextcite` on `\parencite` is at https://github.com/plk/biblatex-apa/compare/master...moewew:nptextcite (https://github.com/moewew/biblatex-apa/tree/nptextcite).

@plk If you like I can prepare a pull request and the same for `apa6`. If not, this can at least serve as a basis for discussion.

**Comment by plk** [comment]
Please feel free to make a PR - this seems fine - `\nptextcite` was really just an afterthought and I never really spent much time on it originally.

**Comment by moewew** [comment]
OK, sent off #103. Let me know how badly this breaks the tests. If all goes well I will look into doing the same (and #102) for `apa6` tomorrow.

**Comment by plk** [comment]
Looks fine - it even corrected an error in the reference doc I use for PDF comparison ...
